### ISSUE TITLE
Links aren't being closed properly by "]" brackets

### ISSUE THREAD

**Issue by sangaline** [plasticboy/vim-markdown#332]
I've been having trouble with the closing `]` on a link not being respected. Here's a screenshot of what happens:

![Syntax Highlighting Issue](https://user-images.githubusercontent.com/8236564/27010933-305e9670-4e7e-11e7-93e6-86d205887613.png)

The contents of that minimal example are:

```
This is filler, but [https://test.com/this/](https://test.com/this) shouldn't be highlighted, right?

This happens a lot with all kinds of links.
```

It seems like this has started happening only recently, but now it's happening very frequently.

**Comment by mvyskoc** [comment]
You can fixit by modifying following line in `vim-markdown\syntax\markdown.vim`
`syn match   mkdInlineURL /\s\@<=https\?:\/\/\(\w\+\(:\w\+\)\?@\)\?\([A-Za-z0-9][-_0-9A-Za-z]*\.\)\{1,}\(\w\{2,}\.\?\)\{1,}\(:[0-9]\{1,5}\)\?\S*/`

I add `\s\@<=` to match the inline links must begin with the space.

**Comment by mvyskoc** [comment]
I am sorry, my previous comment is not correct, because it does not match URL link at the start of the line.
This should work:

`syn match   mkdInlineURL /\%(^\|\s\)\@<=https\?:\/\/\(\w\+\(:\w\+\)\?@\)\?\([A-Za-z0-9][-_0-9A-Za-z]*\.\)\{1,}\(\w\{2,}\.\?\)\{1,}\(:[0-9]\{1,5}\)\?\S*/
`

This means URL link must be at the start of the line or be preceeded with the space.

**Comment by sangaline** [comment]
Thanks, but I actually still get the same behavior with the minimum example that I posted above. Are you able to reproduce the problem?

**Comment by mvyskoc** [comment]
Hi, yes the problem is solved. When you modify the file `vim-markdown\syntax\markdown.vim` you must close the Vim and reopen your `test.md` file again.
I made fork of `vim-markdown` plugin for myself. I made changes that you can follow links with the Enter . You can download only the syntax file from here [markdown.vim](https://github.com/mvyskoc/vim-markdown/blob/master/syntax/markdown.vim)
Here is the diff what I changed:
```diff
diff --git a/syntax/markdown.vim b/syntax/markdown.vim
index 43cb898..1a65dc9 100644
--- a/syntax/markdown.vim
+++ b/syntax/markdown.vim
@@ -66,7 +66,7 @@ execute 'syn region mkdLink matchgroup=mkdDelimiter  start="\\\@<!!\?\[\ze[^]\n]
 " Autolink without angle brackets.
 " mkd  inline links:      protocol     optional  user:pass@  sub/domain                    .com, .co.uk, etc         optional port   path/querystring/hash fragment
 "                         ------------ _____________________ ----------------------------- _________________________ ----------------- __
-syn match   mkdInlineURL /https\?:\/\/\(\w\+\(:\w\+\)\?@\)\?\([A-Za-z0-9][-_0-9A-Za-z]*\.\)\{1,}\(\w\{2,}\.\?\)\{1,}\(:[0-9]\{1,5}\)\?\S*/
+syn match   mkdInlineURL /\%(^\|\s\)\@<=https\?:\/\/\(\w\+\(:\w\+\)\?@\)\?\([A-Za-z0-9][-_0-9A-Za-z]*\.\)\{1,}\(\w\{2,}\.\?\)\{1,}\(:[0-9]\{1,5}\)\?\S*/
 
 " Autolink with parenthesis.
 syn region  mkdInlineURL matchgroup=mkdDelimiter start="(\(https\?:\/\/\(\w\+\(:\w\+\)\?@\)\?\([A-Za-z0-9][-_0-9A-Za-z]*\.\)\{1,}\(\w\{2,}\.\?\)\{1,}\(:[0-9]\{1,5}\)\?\S*)\)\@=" end=")"
```
![image](https://user-images.githubusercontent.com/2125178/27184217-c3e4f36a-51e1-11e7-8b96-80f418c21b9f.png)
![image](https://user-images.githubusercontent.com/2125178/27184241-e2cdcafe-51e1-11e7-99c6-f6604d86d499.png)

**Comment by sangaline** [comment]
It doesn't fix the problem for me. I'm running neovim in Linux, not sure if this might have something to do with the environment.

```
NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
```

My `vim-markdown` config is:

```
" vim-markdown configuration
" ----------------------
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_conceal = 0
let g:vim_markdown_math = 1
let g:tex_conceal = ""
let g:vim_markdown_toml_frontmatter = 1
```

Is there any other information that I could give you that would be helpful?

**Comment by mvyskoc** [comment]
Hi,
I install unstable binary package of `noevim` on Linux Mint 17.3 and the highlighting is working. I don't see any change.

Do you really modify the correct file ? Neovim use configuration folder in `$HOME/.config/nvim` and starts the configuration file `init.vim`. I guess you maybe modified the copy of the plugin which is never run.

You verify that. You create some syntax error in the file `vim-markdown\syntax\markdown.vim`. For example you write `This is error` on the first line.
Now you close vim and reopen your `test.md` file, you should see error as this:
```
"test2.md" 8L, 181C
Chyba při zpracování /home/martin/.config/nvim/bundle/vim-markdown/syntax/markdown.vim:
řádek    1:
E492: Not an editor command: This is syntax error
E492: Not an editor command: This is syntax error
Press ENTER or type command to continue
```
If you will not get any error, Neovim does not process this file at all and you must find why. 
For example I made this stupid mistake. I copied all my configuration files from common `~/.vim` to `~/.confing/nvim`. The content of my `init.vim` was `source ~/.config/nvim/vimrc`. But the original `vimrc` file included absolute paths to `~/.vim` folder. I totalty did not use plugins from `~/.confing/nvim` . Try to look if you have not simillar problem.

My version of neovim:
```
:version                                                                                                      
NVIM v0.2.1-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-sec
urity -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DMIN_LOG_LEVEL=3 -Wall -Wextr
a -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCL
UDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-YR5pS9/neovim-0.2.0ubuntu1+git201706141832+3473+26~ubuntu14.04.1
/build/config -I/build/neovim-YR5pS9/neovim-0.2.0ubuntu1+git201706141832+3473+26~ubuntu14.04.1/src -I/build/neovim-YR5pS9
/neovim-0.2.0ubuntu1+git201706141832+3473+26~ubuntu14.04.1/.deps/usr/include -I/build/neovim-YR5pS9/neovim-0.2.0ubuntu1+g
it201706141832+3473+26~ubuntu14.04.1/.deps/usr/include -I/build/neovim-YR5pS9/neovim-0.2.0ubuntu1+git201706141832+3473+26
~ubuntu14.04.1/.deps/usr/include -I/build/neovim-YR5pS9/neovim-0.2.0ubuntu1+git201706141832+3473+26~ubuntu14.04.1/.deps/u
sr/include -I/build/neovim-YR5pS9/neovim-0.2.0ubuntu1+git201706141832+3473+26~ubuntu14.04.1/.deps/usr/include -I/build/ne
ovim-YR5pS9/neovim-0.2.0ubuntu1+git201706141832+3473+26~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-YR
5pS9/neovim-0.2.0ubuntu1+git201706141832+3473+26~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-YR5pS9/neovim-0.2.0ubu
ntu1+git201706141832+3473+26~ubuntu14.04.1/build/include
přeložil  root@lgw01-15

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences
```

**Comment by sangaline** [comment]
So I did get the error, but it turns out that there was a second copy of `vim-markdown` provided by `vim-polyglot` and that is what was doing the highlighting. Explicitly disabling that version with `let g:polyglot_disabled = ['markdown']` allowed the separately installed version to take over properly.

All resolved now, thanks!
